### PR TITLE
Fixes logout button

### PR DESCRIPTION
**Pull request by MiscLG**
The logout button should work now. My concern with how I did it is that I send a parameter through an href. I feel like there could be a method that does not show the statement in the developer tools on the browser.

### CODE REVIEW

**Comment by MiscLG** [comment]
You can see how it works here [https://0-luis-dot-team23-project.appspot.com/](url).

**Comment by MiscLG** [comment]
You can see the change here [https://0-luis-dot-team23-project.appspot.com/](url).

**Comment by MiscLG** [comment]
This is the link to my version with this feature working.  https://0-luis-dot-team23-project.appspot.com/

**Review by tbiscuit — APPROVED** [review]
Nice one! Good to have that working!!

**Pull request merged**
